version: "3"

services:
 api:
   build:
      context: .
      dockerfile: api/Dockerfile
  #  image: nextasy01/url-shortener:latest
   ports:
     - "9000:9000"
   depends_on:
     - db 
 db:
    # build:
    #     context: .
    #     dockerfile: db/Dockerfile
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - .data:/data  