version: "3"

services:
 api:
   build:
      context: .
      dockerfile: api/Dockerfile
   ports:
     - "6600:6600"
   depends_on:
     - db 
 db:
    build:
        context: .
        dockerfile: db/Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - .data:/data  